//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

namespace Machine.Specifications.Mvc.Specs
{
    using System.Web.Mvc;

    [Subject(typeof(PartialViewResultAnd))]
    public class when_the_partial_view_result_and_is_asked_for_the_and_bit
    {
        static PartialViewResultAnd viewResultAnd;
        static PartialViewResult viewResult;
        static PartialViewResult result;

        Establish context = () =>
            {
                viewResult = new PartialViewResult();
                viewResultAnd = new PartialViewResultAnd(viewResult);
            };

        Because of = () => result = viewResultAnd.And();

        It should_return_the_partial_view_result = () => result.ShouldEqual(viewResult);
    }
}   