//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.9.3.0")]
[assembly: AssemblyFileVersion("1.9.3.0")]
[assembly: AssemblyCopyright("Copyright (c) James Broome 2016")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("James Broome")]
[assembly: AssemblyProduct("Machine.Specifications.Mvc is a set of extensions for testing ASP.Net MVC specifi" +
    "c types. \r\n\r\nIt aims to ease the testing of ActionResult objects returned from M" +
    "VC Controllers by providing an MSpec BDD syntax over these types. (Debug DB: 1)")]


